env:
  browser: true
  es6: true
extends: eslint:recommended
parserOptions:
  sourceType: module
rules:
  no-console:
    - 1
  linebreak-style:
    - 1
    - unix
  indent:
    - 1
    - 2
    - SwitchCase: 1
  quotes:
    - 1
    - single
  space-in-parens:
    - 1
    - always
  space-before-blocks:
    - 1
  space-before-function-paren:
    - 1
    - never
  brace-style:
    - 1
  no-mixed-spaces-and-tabs:
    - 1
  no-trailing-spaces:
    - 1
  key-spacing:
    - 1
  keyword-spacing:
    - 1
  prefer-arrow-callback:
    - 1
  prefer-const:
    - 1
  no-var:
    - 1
  semi:
    - 2
    - always
  strict:
    - 2
    - function
  curly:
    - 2
  eqeqeq:
    - 2
    - smart
  one-var:
    - 2
    - never
  no-implicit-globals:
    - 2
  no-redeclare:
    - 2
  no-loop-func:
    - 2
  no-undef:
    - 2
